// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uotnlwovxytmobggyokp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvdG5sd292eHl0bW9iZ2d5b2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzkwNTAsImV4cCI6MjA3MTAxNTA1MH0.KtgpEy3255QMgVEUpLRuGFbKp4CCucN9OswmgckxFjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});