// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxnsmqvqvujbpyszkuck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4bnNtcXZxdnVqYnB5c3prdWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzODg2MjYsImV4cCI6MjA2Nzk2NDYyNn0.0NhIK4XHZuHgIJMFVGj540NjsYSRG8VcKuViAdp-KCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});